# Generated by Django 5.2.8 on 2025-12-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0002_alter_usuario_email_alter_usuario_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Produto"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Produto")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço (R$)"
                    ),
                ),
                (
                    "quantidade_estoque",
                    models.PositiveIntegerField(verbose_name="Quantidade em Estoque"),
                ),
                (
                    "estoque_minimo",
                    models.PositiveIntegerField(verbose_name="Estoque Mínimo"),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="TransicaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                        max_length=10,
                        verbose_name="Tipo de Transição",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Transição Financeira",
                "verbose_name_plural": "Transições Financeiras",
            },
        ),
    ]
