# Generated by Django 6.0.4 on 2026-04-26 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestao', '0003_produtos_transicaofinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do produto')),
                ('descricao', models.TextField(verbose_name='descrição do produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço (R$)')),
                ('quantidade_estoque', models.PositiveIntegerField(verbose_name='quantidade em estoque')),
                ('estoque_minimo', models.PositiveIntegerField(verbose_name='estoque mínimo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('descricao', models.TextField(verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
            },
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.DeleteModel(
            name='TransicaoFinanceira',
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterUniqueTogether(
            name='jornadatrabalho',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='estaAtivo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='esta_ativo',
            field=models.BooleanField(default=True, verbose_name='está ativo'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.clienteprofile', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(verbose_name='fim do agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='início do agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.funcionario', verbose_name='profissional'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.servico', verbose_name='serviço'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (aguardando confirmação)'), ('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído (serviço pago)'), ('CANCELADO', 'Cancelado'), ('NO_SHOW', 'Não compareceu')], db_index=True, default='PENDENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='valor_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor cobrado (R$)'),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='usuário de login'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='especializacao',
            field=models.CharField(max_length=100, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário de login'),
        ),
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='dia_da_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana'),
        ),
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.funcionario', verbose_name='funcionário'),
        ),
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='hora_fim',
            field=models.TimeField(verbose_name='hora de fim do expediente'),
        ),
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='hora_inicio',
            field=models.TimeField(verbose_name='hora de início do expediente'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(verbose_name='descrição do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(verbose_name='duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço (R$)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos aos quais o usuário pertence.', related_name='gestao_usuario_set', related_query_name='usuario', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadatrabalho',
            unique_together={('funcionario', 'dia_da_semana')},
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['profissional', 'data_hora_inicio', 'data_hora_fim'], name='idx_agendamento_conflito'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='gestao.agendamento', verbose_name='agendamento de origem'),
        ),
    ]
