# Generated by Django 6.0.4 on 2026-05-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_produto_transacaofinanceira_delete_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='celular'),
        ),
    ]
