# Generated by Django 6.0.6 on 2026-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_celular_nullable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('data_hora_fim__gt', models.F('data_hora_inicio'))), name='agendamento_fim_depois_inicio'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='servico_preco_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_minutos__gte', 1)), name='servico_duracao_positiva'),
        ),
    ]
