# Generated by Django 6.0.6 on 2026-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_agendamento_agendamento_fim_depois_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipe/', verbose_name='foto do profissional'),
        ),
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='foto do serviço'),
        ),
    ]
