# Generated by Django 5.2.8 on 2025-12-31 13:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('celular', models.CharField(max_length=15, unique=True, verbose_name='celular')),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos do usuário pertence.', related_name='gestao_usuario_set', related_query_name='usuario', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas deste usuário.', related_name='gestao_usuario_permissions', related_query_name='usuario_permission', to='auth.permission', verbose_name='permissões de usuário')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Servico')),
                ('descricao', models.TextField(verbose_name='Descricao do Servico')),
                ('duracao_minutos', models.PositiveIntegerField(verbose_name='Duracao (minutos)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco (R$)')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
            },
        ),
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Login')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especializacao', models.CharField(max_length=100, verbose_name='Cargo')),
                ('estaAtivo', models.BooleanField(default=True, verbose_name='Está Ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Login')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Início do Agendamento')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Fim do Agendamento')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Confirmação)'), ('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído (Serviço Pago)'), ('CANCELADO', 'Cancelado'), ('NO_SHOW', 'Não Compareceu')], default='PENDENTE', max_length=15)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.funcionario', verbose_name='Profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agendamento.servico', verbose_name='Servico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.clienteprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início do Expediente')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim do Expediente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Jornada de Trabalho',
                'verbose_name_plural': 'Jornadas de Trabalho',
                'unique_together': {('funcionario', 'dia_da_semana', 'hora_inicio')},
            },
        ),
    ]
